<?php

define('LECTURN_PROPERTIES_BG', '#cccccc');
define('LECTURN_PROPERTIES_FG', '#000000');
define('LECTURN_PROPERTIES_LINK', '#820002');
define('LECTURN_PROPERTIES_SEARCH', '#999999');
define('LECTURN_BANNER_BG', '#071533');
define('LECTURN_BANNER_FG', '#ffffff');
define('LECTURN_BANNER_LINK_NORMAL', '#d4d1ae');
define('LECTURN_BANNER_LINK_HOVER', '#d4d1ae');
define('LECTURN_BANNER_TITLE', '#d4d1ae');
define('LECTURN_BANNER_BOTTOM', '#91bed4');
define('LECTURN_PAGES_BG', '#333344');
define('LECTURN_PAGES_FG', '#ffffff');
define('LECTURN_PAGES_LINK_NORMAL', '#ffffff');
define('LECTURN_PAGES_LINK_HOVER', '#d4d1ae');
define('LECTURN_PAGES_BORDER', '#666666');
define('LECTURN_SPOTLIGHT_BG', '#d9e8f5');
define('LECTURN_SPOTLIGHT_FG', '#000000');
define('LECTURN_SPOTLIGHT_LINK_NORMAL', '#db5801');
define('LECTURN_SPOTLIGHT_LINK_HOVER', '#b9121b');
define('LECTURN_SPOTLIGHT_CAL_NORMAL', '#db5801');
define('LECTURN_SPOTLIGHT_CAL_HOVER', '#b9121b');
define('LECTURN_SPOTLIGHT_BOTTOM', '#91bed4');
define('LECTURN_CONTENT_BG', '#ffffff');
define('LECTURN_CONTENT_FG', '#333333');
define('LECTURN_CONTENT_LINK_NORMAL', '#db5801');
define('LECTURN_CONTENT_LINK_HOVER', '#ff020f');
define('LECTURN_CONTENT_PRE_FG', '#000000');
define('LECTURN_CONTENT_PRE_BG', '#dddddd');
define('LECTURN_CONTENT_HEADER_BOTTOM', '#333333');
define('LECTURN_CONTENT_BOTTOM', '#c9d8f5');

?>
